{
 "title": "투싼 ICCU 결함 이슈 모니터링 시스템",
 "time": { "from": "2017-06-17T00:00:00.000Z", "to": "2024-06-30T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "selectedDate" },
   { "name": "linkDate" },
   { "name": "linkDate2" },
   { "name": "linkCar" }
  ]
 },
 "panels": [
  { "title": " ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://github.com/ssangmin-junior/softeer_wiki/blob/main/files/HyunDE.png?raw=true\" alt=\"Google Drive Image\">"
   },
   "targets": [
    { "dataset": "Dashboard" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 1 },
   "options": {
    "content": "<img src=\"https://github.com/ssangmin-junior/softeer_wiki/blob/main/files/logogo.png?raw=true\" alt=\"Google Drive Image\">"
   },
   "targets": [
    { "dataset": "Dashboard" }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 1 },
   "targets": [
    {
     "dataset": "Dashboard",
     "rawSql": "SELECT * FROM Dashboard.Scores LIMIT 50 "
    }
   ]
  },
  { "title": "\bLive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Live Watch",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "Dashboard",
     "queryText": "SELECT UNIX_TIMESTAMP(DateTime) as time, score FROM score_df WHERE CarName = '투싼' ORDER BY DateTime;",
     "rawQueryText": "SELECT UNIX_TIMESTAMP(DateTime) as time, score FROM score_df WHERE CarName = '투싼' ORDER BY DateTime;",
     "rawSql": "SELECT UNIX_TIMESTAMP(CONVERT_TZ(DateTime, '+09:00', 'SYSTEM')) as time, IncreaseScore FROM Dashboard.IncreaseScoreTable LIMIT 50 ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Most Increasing Post",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 11, "y": 6 },
   "targets": [
    {
     "dataset": "Dashboard",
     "rawSql": "SELECT Title,Content,URL FROM Dashboard.MostIncreasingPostTable ORDER BY DateTime DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Contents having Keywords",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 10 },
   "targets": [
    {
     "dataset": "Dashboard",
     "rawSql": "SELECT Content, URL FROM Dashboard.NewContentHavingKeywordTable\nWHERE DateTime IN (SELECT DateTime FROM Dashboard.IncreaseScoreTable ORDER BY Datetime DESC);"
    }
   ]
  },
  { "title": "Similar Case", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Similarity",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "Dashboard",
     "rawSql": "SELECT \n    s.SimilarCar as Vehicle,\n    DATE_FORMAT(s.SimilarDate, '%Y-%m-%d') AS Date,\n    s.Similarity,\n    i.DeviceCategory as Defect,\n    i.TargetQuantity as Quantity\nFROM \n    Dashboard.Similarity s\nLEFT JOIN \n    Dashboard.Issues i\nON \n    s.SimilarCar = i.CarName\nAND \n    s.SimilarDate = i.Date\nORDER BY \n    i.DeviceCategory IS NULL,  -- Defect가 NULL인 행을 뒤로 배치\n    s.Similarity DESC           -- Similarity 값에 따라 내림차순 정렬\nLIMIT 50;\n"
    }
   ]
  },
  {
   "title": "Similar Graph",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 9, "w": 14, "x": 9, "y": 18 },
   "targets": [
    {
     "dataset": "Dashboard",
     "rawSql": "WITH AlignedData AS (\n    SELECT\n        GREATEST(\n            (SELECT MIN(Date) FROM TucsonScores WHERE CarName = '투싼'),\n            (SELECT MIN(Date) FROM Scores WHERE CarName = (SELECT SimilarCar FROM Similarity WHERE BaseCar = '투싼' ORDER BY Similarity DESC LIMIT 1))\n        ) AS AlignDate\n)\n\nSELECT\n    UNIX_TIMESTAMP(ts.Date) AS time,\n    ts.CarName,\n    ts.Score\nFROM\n    TucsonScores ts\nWHERE\n    ts.CarName = '투싼'\n    AND ts.Date >= (SELECT AlignDate FROM AlignedData)\nORDER BY\n    ts.Date ASC;"
    },
    {
     "dataset": "Dashboard",
     "rawSql": "WITH SimilarCar AS (\n    SELECT\n        SimilarCar,\n        SimilarDate,\n        ClosestIssueDate,  -- ClosestIssueDate를 정확히 참조\n        DATE_SUB(SimilarDate, INTERVAL 7 DAY) AS StartDate,\n        DATE_ADD(SimilarDate, INTERVAL 7 DAY) AS EndDate\n    FROM\n        Similarity\n    WHERE\n        BaseCar = '투싼'\n        AND SimilarDate = '$selectedDate'  -- 선택된 날짜를 변수로 사용\n    ORDER BY\n        Similarity DESC\n    LIMIT 1\n), AlignedData AS (\n    SELECT\n        MIN(Date) AS BaseStartDate,\n        MAX(Date) AS BaseEndDate\n    FROM\n        TucsonScores\n    WHERE\n        CarName = '투싼'\n), DateDiffs AS (\n    SELECT\n        DATEDIFF(AlignedData.BaseStartDate, SimilarCar.StartDate) AS DateShift\n    FROM\n        SimilarCar,\n        AlignedData\n)\n\nSELECT\n    UNIX_TIMESTAMP(DATE_ADD(s.Date, INTERVAL DateDiffs.DateShift DAY)) AS time,\n    s.CarName,\n    s.Score,\n    DATE_FORMAT(DATE_ADD(sim.ClosestIssueDate, INTERVAL DateDiffs.DateShift DAY), '%Y-%m-%d %H:%i:%s') AS closest_issue_time  -- ClosestIssueDate를 이동된 날짜에 맞춰서 변경\nFROM\n    Scores s\nJOIN\n    SimilarCar sim\n    ON s.CarName = sim.SimilarCar\nJOIN\n    DateDiffs\nWHERE\n    s.Date BETWEEN sim.StartDate AND sim.EndDate\nORDER BY\n    s.Date ASC;\n"
    }
   ]
  },
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Base",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "Dashboard",
     "rawSql": "WITH AlignedData AS (\n    SELECT\n        GREATEST(\n            (SELECT MIN(Date) FROM TucsonScores WHERE CarName = '투싼'),\n            (SELECT MIN(Date) FROM Scores WHERE CarName = (SELECT SimilarCar FROM Similarity WHERE BaseCar = '투싼' ORDER BY Similarity DESC LIMIT 1))\n        ) AS AlignDate\n)\n\nSELECT\n    UNIX_TIMESTAMP(ts.Date) AS time,\n    ts.CarName\nFROM\n    TucsonScores ts\nWHERE\n    ts.CarName = '투싼'\n    AND ts.Date >= (SELECT AlignDate FROM AlignedData)\nORDER BY\n    ts.Date ASC;\n"
    }
   ]
  },
  {
   "title": "Sentiment Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "Dashboard",
     "rawSql": "SELECT Negative, Positive FROM Dashboard.TucsonSentimentCount WHERE Date = '${linkDate}' LIMIT 50"
    }
   ]
  },
  {
   "title": "Comment WordCloud",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 28 },
   "targets": [
    {
     "dataset": "Dashboard",
     "rawSql": "SELECT Frequency, Word FROM Dashboard.TucsonWordFrequency WHERE Date = '${linkDate}' LIMIT 50"
    }
   ]
  },
  {
   "title": "Hot Issue",
   "type": "canvas",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 28 },
   "targets": [
    {
     "dataset": "Dashboard",
     "rawSql": "SELECT \n  Title, \n  Content, \n  URL\nFROM \n  Dashboard.TucsonPosts\nWHERE \n  DATE_FORMAT(DateTime, '%Y-%m-%d') = '${linkDate}'"
    }
   ]
  }
 ]
}